
spring:
  datasource:   #配置数据库的信息
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wildms?useSSL=false
    username: root
    password: 1111
    type: com.alibaba.druid.pool.DruidDataSource #数据源类型
  thymeleaf:
    cache: false #thymeleaf关闭缓存，可以在修改代码后不需要重启服务器


mybatis:
  type-aliases-package: com.fan1111.entity #给实体类类起别名
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #设置将sql打印到控制台

#定义视图前缀
#spring.mvc.view.prefix=/WEB-INF/jsp/
#定义视图后缀
#spring.mvc.view.suffix=.jsp


#配置集成tomcat的端口，可自行修改
server:
  port: 80


#标记mapper文件的路径，如果报找不到mapper错误时启用
#mybatis.mapper-locations=classpath:com/fan1111/mapper/*.xml